server:
  port: 8888
spring:
  application:
    name: gateway-service #sets the name of the Spring Boot application to gateway-service
  cloud:
    discovery:
      enabled: true # means the gateway can route requests dynamically to different services without manually specifying the service addresses in the configuration.
#    gateway:
#      routes:
#        - id: r1
#          uri: http://localhost:8081
#          predicates:
#            - Path= /customers/**
#        - id: r2
#          uri: http://localhost:8082
#          predicates:
#            - Path= /products/**
#
